### ISSUE TITLE
Max number of clips/threads in an example?

### ISSUE THREAD

**Issue by vineetparikh** [willprice/epic-kitchens-activity-stories#2]
Thanks for the really excellent work and annotations! I just had a quick question about clips/threads.

What is the highest number of clips and threads in a GT example? Many of the figures (e.g. Fig 7) indicate lots of clips (~40 clips) and potentially many threads (up to 4 threads), but it looks like the GT annotations have a smaller number of clips and a smaller number of real threads. I just want to make sure I'm reading the data correctly as I'm exploring it.

Thanks in advance for your help!
Vineet

**Comment by dimadamen** [comment]
Thanks for your interest. As we noted in Sec 4, all annotated train/val/test consists of 10 clips exactly for training, while testing clips vary from 5 to 26 clips. This is what we have released and it matches Table 1 and all quantitative results.
Indeed we qualitatively analysed longer stories of 40 clips qualitatively and provided examples of these such as Fig 7. 
As you can see in Fig 7, there's no ground-truth here (bottom right corner is the ground truth as in other figures - for example Fig 8). So this was simply done qualitatively to showcase the model's capability for longer clips.
I understand you are enquiring as to the location of these clips in our videos? I can tell you the start-end time of this Figure's representation (needs some digging) but there's no corresponding annotations/ground truth.
