### ISSUE TITLE
Correspondences between activity story clips and clips in original EPIC-Kitchens 100 annotations

### ISSUE THREAD

**Issue by vineetparikh** [willprice/epic-kitchens-activity-stories#3]
Hi there, quick question: is there any clear correspondence between the activity story clips in this repository and the clip boundaries representing individual actions in the original EPIC-Kitchens annotations repo? If not, what was the general approach for distinguishing different clips in an example? This was something I was a bit confused on from reading through the paper fully, thanks in advance for your help in clarification!

**Comment by vineetparikh** [comment]
Hi there, any updates?

**Comment by dimadamen** [comment]
Please read appendix B in our paper for details of how the 1-second clips were selected. These have nothing to do with start-end times of actions. The distinction is the fine-grained actions of the latter while our clips focus purely on task switching. 
In short, action clips in EPIC-KITCHENS annotations are not related in any way to stories in Unweavenet.
